version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    timezone: America/New_York
  open-pull-requests-limit: 10
  labels:
  - dependencies
  ignore:
  - dependency-name: chai
    versions:
    - 4.3.2
